/**
 * Job API Schema Mappings
 * 
 * Aligned with OData endpoint: /odata/iworks/v1/Jobs
 * Based on OpenAPI schema from http://localhost:8090/odata-doc/odata/iworks/v1/openapi.json
 */

import { Job, CreateJobRequest } from '@/types';

/**
 * API Field Mapping for Jobs
 * Maps OData backend fields to frontend Job interface
 * 
 * OData Schema Fields:
 * - JobID (string, required for CREATE, read-only UUID)
 * - JobName (string)
 * - Description (string)
 * - Status (enum: Scheduled | In_Progress | Completed | Canceled)
 * - Priority (enum: Low | Medium | High | Critical)
 * - ScheduledDate (date-time, ISO 8601)
 * - StartDate (date-time, ISO 8601)
 * - EndDate (date-time, ISO 8601)
 * - Location (string)
 * - EstimatedDuration (integer, in minutes)
 * - EventAllDay (boolean)
 * - changedDate (date-time, read-only)
 * - createdDate (date-time, read-only)
 * 
 * Expandable Relations:
 * - Job_AssignedTo (Employee)
 * - Customer
 */
export const JOB_FIELD_MAP = {
  // Backend → Frontend
  JobID: 'id',
  JobName: 'title',
  Description: 'description',
  Status: 'status',
  Priority: 'priority',
  ScheduledDate: 'date',
  StartDate: 'startDate',
  EndDate: 'endDate',
  Location: 'location',
  EstimatedDuration: 'estimatedDuration',
  EventAllDay: 'eventAllDay',
  changedDate: 'changedDate',
  createdDate: 'createdDate',
} as const;

/**
 * GET: Transform OData Job response → Frontend Job interface
 * Used by: getAllJobs(), getJobById()
 * 
 * Note: assignedTo is handled separately as it's an expandable relation (Job_AssignedTo)
 */
export const transformJobFromApi = (apiJob: any): Job => {
  console.log('[Job Schema] Transforming job from API:', apiJob?.JobID || 'unknown');
  
  return {
    id: Number(apiJob.JobID),
    tenantId: apiJob.TenantId || '',
    title: apiJob.JobName || '',
    description: apiJob.Description || '',
    status: apiJob.Status || 'Scheduled',
    priority: apiJob.Priority || 'Medium',
    date: apiJob.ScheduledDate || new Date().toISOString(),
    startDate: apiJob.StartDate || undefined,
    endDate: apiJob.EndDate || undefined,
    location: apiJob.Location || '',
    estimatedDuration: apiJob.EstimatedDuration || undefined,
    eventAllDay: apiJob.EventAllDay || false,
    assignedTo: apiJob.Job_AssignedTo?.FullName || apiJob.Job_AssignedTo?.Email || '',
    // Map JobLineItems to lineItems (services and materials)
    lineItems: Array.isArray(apiJob.JobLineItems)
      ? apiJob.JobLineItems.map((item: any) => ({
          id: item.LineItemID ? Number(item.LineItemID) : undefined,
          itemType: item.ItemType || 'Product',
          name: item.Name || '',
          description: item.Description || '',
          quantity: item.Quantity || 0,
          unitPrice: item.UnitPrice || 0,
          totalPrice: item.TotalPrice || 0,
        }))
      : [],
    // Map Pricing from expanded relation
    pricing: apiJob.Pricing ? {
      id: Number(apiJob.Pricing.PriceID),
      tenantId: apiJob.TenantId || '',
      subTotal: Number(apiJob.Pricing.SubTotal) || 0,
      discount: Number(apiJob.Pricing.Discount) || 0,
      taxRate: Number(apiJob.Pricing.TaxRate) || 0,
      taxAmount: Number(apiJob.Pricing.TaxAmount) || 0,
      total: Number(apiJob.Pricing.Total) || 0,
      county: apiJob.Pricing.County || undefined,
      jobId: Number(apiJob.JobID),
    } : undefined,
    changedDate: apiJob.changedDate,
    createdDate: apiJob.createdDate,
  };
};

/**
 * POST: Transform Create Request → OData JobCREATE format
 * Used by: createJob()
 * 
 * Schema: JobCREATE
 * - JobID is auto-generated by backend (server-side)
 * - All fields are optional except those required by business logic
 * - changedDate and createdDate are auto-generated by server
 * - JobLineItems are included as nested array if present
 * 
 * Note: JobID is NOT included - backend handles ID generation
 */
export const transformCreateJobToApi = (jobData: CreateJobRequest): any => {
  console.log('[Job Schema] Transforming CREATE job to API format');
  console.log('[Job Schema] Line items count:', jobData.lineItems?.length || 0);
  
  const payload: any = {
    // JobID is NOT included - backend auto-generates it
    JobName: jobData.title || '',
    Description: jobData.description || null,
    Status: jobData.status || 'Scheduled', // Default: Scheduled
    Priority: jobData.priority || 'Medium', // Default: Medium
    ScheduledDate: jobData.scheduledDate || new Date().toISOString(),
    StartDate: jobData.startDate || null,
    EndDate: jobData.endDate || null,
    Location: jobData.location || null,
    EstimatedDuration: jobData.estimatedDuration || null, // In minutes
    EventAllDay: jobData.eventAllDay || false,
    // Note: JobID, changedDate, and createdDate are auto-generated by server
  };

  // Add line items if present
  if (jobData.lineItems && jobData.lineItems.length > 0) {
    payload.JobLineItems = jobData.lineItems.map(item => ({
      Name: item.name || '',
      Description: item.description || '',
      Quantity: item.quantity || 0,
      UnitPrice: item.unitPrice || 0,
      TotalPrice: item.totalPrice || 0,
      UnitCost: item.unitPrice || 0, // Default UnitCost to UnitPrice if not provided
      ItemType: item.itemType || 'Product', // 'Service' or 'Product'
      Markup: 0, // Default markup to 0
      IsTaxExempt: false, // Default to taxable
    }));
    console.log('[Job Schema] Mapped', payload.JobLineItems.length, 'line items');
  }

  return payload;
};

/**
 * PATCH: Transform Update Request → OData JobUPDATE format
 * Used by: updateJob()
 * 
 * Schema: JobUPDATE
 * - JobID is NOT included (passed in URL path)
 * - Only include fields that are being updated
 * - changedDate is auto-updated by server
 */
export const transformUpdateJobToApi = (job: Partial<Job>): any => {
  console.log('[Job Schema] Transforming UPDATE job to API format:', job?.id || 'unknown');
  
  const updateData: any = {};
  
  // Only include fields that are provided
  if (job.title !== undefined) updateData.JobName = job.title;
  if (job.description !== undefined) updateData.Description = job.description;
  if (job.status !== undefined) updateData.Status = job.status;
  if (job.priority !== undefined) updateData.Priority = job.priority;
  if (job.date !== undefined) updateData.ScheduledDate = job.date;
  if (job.startDate !== undefined) updateData.StartDate = job.startDate;
  if (job.endDate !== undefined) updateData.EndDate = job.endDate;
  if (job.location !== undefined) updateData.Location = job.location;
  if (job.estimatedDuration !== undefined) updateData.EstimatedDuration = job.estimatedDuration;
  if (job.eventAllDay !== undefined) updateData.EventAllDay = job.eventAllDay;
  
  return updateData;
};

/**
 * Legacy transformer for backward compatibility
 * @deprecated Use transformUpdateJobToApi instead
 */
export const transformJobToApi = transformUpdateJobToApi;
