/**
 * Pricing API Schema Mappings
 * 
 * Aligned with OData endpoint: /odata/iworks/v1/Pricing
 * Based on OData v4 standard
 */

import { Pricing, CreatePricingRequest } from '@/types';

/**
 * API Field Mapping for Pricing
 * Maps OData backend fields to frontend Pricing interface
 * 
 * OData Schema Fields:
 * - PricingID (integer, required for CREATE, read-only)
 * - SubTotal (decimal)
 * - Discount (decimal)
 * - TaxRate (decimal)
 * - TaxAmount (decimal)
 * - Total (decimal)
 * - County (string)
 * - JobID (integer, foreign key)
 * - changedDate (date-time, read-only)
 * - createdDate (date-time, read-only)
 * 
 * Expandable Relations:
 * - Job (Job entity via JobID foreign key)
 */
export const PRICING_FIELD_MAP = {
  // Backend → Frontend
  PricingID: 'id',
  SubTotal: 'subTotal',
  Discount: 'discount',
  TaxRate: 'taxRate',
  TaxAmount: 'taxAmount',
  Total: 'total',
  County: 'county',
  JobID: 'jobId',
  changedDate: 'changedDate',
  createdDate: 'createdDate',
} as const;

/**
 * GET: Transform OData Pricing response → Frontend Pricing interface
 * Used by: getAllPricing(), getPricingById()
 * 
 * Note: job is handled separately as it's an expandable relation
 */
export const transformPricingFromApi = (apiPricing: any): Pricing => {
  console.log('[Pricing Schema] Transforming pricing from API:', apiPricing?.PricingID || 'unknown');
  
  return {
    id: Number(apiPricing.PricingID),
    tenantId: apiPricing.TenantId || '',
    subTotal: Number(apiPricing.SubTotal) || 0,
    discount: Number(apiPricing.Discount) || 0,
    taxRate: Number(apiPricing.TaxRate) || 0,
    taxAmount: Number(apiPricing.TaxAmount) || 0,
    total: Number(apiPricing.Total) || 0,
    county: apiPricing.County || '',
    jobId: apiPricing.JobID ? Number(apiPricing.JobID) : undefined,
    // Handle expanded Job relation if present
    job: apiPricing.Job ? {
      id: Number(apiPricing.Job.JobID),
      tenantId: apiPricing.Job.TenantId || '',
      title: apiPricing.Job.JobName || '',
      description: apiPricing.Job.Description || '',
      status: apiPricing.Job.Status || 'Scheduled',
      priority: apiPricing.Job.Priority || 'Medium',
      date: apiPricing.Job.ScheduledDate || new Date().toISOString(),
      startDate: apiPricing.Job.StartDate || undefined,
      endDate: apiPricing.Job.EndDate || undefined,
      location: apiPricing.Job.Location || '',
      estimatedDuration: apiPricing.Job.EstimatedDuration || undefined,
      eventAllDay: apiPricing.Job.EventAllDay || false,
      assignedTo: apiPricing.Job.Job_AssignedTo?.FullName || apiPricing.Job.Job_AssignedTo?.Email || '',
      changedDate: apiPricing.Job.changedDate,
      createdDate: apiPricing.Job.createdDate,
    } : undefined,
    changedDate: apiPricing.changedDate,
    createdDate: apiPricing.createdDate,
  };
};

/**
 * POST: Transform Create Request → OData PricingCREATE format
 * Used by: createPricing()
 * 
 * Schema: PricingCREATE
 * - PricingID is auto-generated by backend (server-side)
 * - All fields are optional except SubTotal
 * - changedDate and createdDate are auto-generated by server
 * 
 * Note: PricingID is NOT included - backend handles ID generation
 */
export const transformCreatePricingToApi = (pricingData: CreatePricingRequest): any => {
  console.log('[Pricing Schema] ========== TRANSFORM TO API ==========');
  console.log('[Pricing Schema] Input data:', pricingData);
  
  const payload: any = {
    // PricingID is NOT included - backend auto-generates it
    SubTotal: pricingData.subTotal || 0,
    Discount: pricingData.discount || 0,
    TaxRate: pricingData.taxRate || 0,
    TaxAmount: pricingData.taxAmount || 0,
    Total: pricingData.total || 0,
    County: pricingData.county || null,
    // Note: PricingID, changedDate, and createdDate are auto-generated by server
  };

  // Add Job binding if jobId is provided
  if (pricingData.jobId) {
    payload['Job@odata.bind'] = `Jobs(${pricingData.jobId})`;
    console.log('[Pricing Schema] ✓ Job binding added: Jobs(' + pricingData.jobId + ')');
  }

  console.log('[Pricing Schema] ✓ API Payload (will be sent to POST /odata/iworks/v1/Pricing):', JSON.stringify(payload, null, 2));
  console.log('[Pricing Schema] Field verification:');
  console.log('[Pricing Schema]   - SubTotal:', payload.SubTotal);
  console.log('[Pricing Schema]   - Discount:', payload.Discount);
  console.log('[Pricing Schema]   - TaxRate:', payload.TaxRate);
  console.log('[Pricing Schema]   - TaxAmount:', payload.TaxAmount);
  console.log('[Pricing Schema]   - Total:', payload.Total);
  console.log('[Pricing Schema]   - County:', payload.County);
  console.log('[Pricing Schema]   - Job@odata.bind:', payload['Job@odata.bind']);
  console.log('[Pricing Schema] ===================================');
  
  return payload;
};

/**
 * PATCH: Transform Update Request → OData PricingUPDATE format
 * Used by: updatePricing()
 * 
 * Schema: PricingUPDATE
 * - PricingID is NOT included (passed in URL path)
 * - Only include fields that are being updated
 * - changedDate is auto-updated by server
 */
export const transformUpdatePricingToApi = (pricing: Partial<Pricing>): any => {
  console.log('[Pricing Schema] Transforming UPDATE pricing to API format:', pricing?.id || 'unknown');
  
  const updateData: any = {};
  
  // Only include fields that are provided
  if (pricing.subTotal !== undefined) updateData.SubTotal = pricing.subTotal;
  if (pricing.discount !== undefined) updateData.Discount = pricing.discount;
  if (pricing.taxRate !== undefined) updateData.TaxRate = pricing.taxRate;
  if (pricing.taxAmount !== undefined) updateData.TaxAmount = pricing.taxAmount;
  if (pricing.total !== undefined) updateData.Total = pricing.total;
  if (pricing.county !== undefined) updateData.County = pricing.county;
  
  // Update Job binding if jobId is provided
  if (pricing.jobId !== undefined) {
    if (pricing.jobId === null) {
      // Remove job association
      updateData['Job@odata.bind'] = null;
    } else {
      updateData['Job@odata.bind'] = `Jobs(${pricing.jobId})`;
    }
  }
  
  return updateData;
};

/**
 * Legacy transformer for backward compatibility
 * @deprecated Use transformUpdatePricingToApi instead
 */
export const transformPricingToApi = transformUpdatePricingToApi;
